# Generated by Django 4.0.4 on 2022-04-27 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aircraft',
            old_name='e_class_seats',
            new_name='aircraft_eClassSeats',
        ),
        migrations.RenameField(
            model_name='aircraft',
            old_name='f_class_seats',
            new_name='aircraft_fClassSeats',
        ),
        migrations.RenameField(
            model_name='aircraft',
            old_name='s_class_seats',
            new_name='aircraft_sClassSeats',
        ),
        migrations.RemoveField(
            model_name='airport',
            name='id',
        ),
        migrations.AddField(
            model_name='airport',
            name='airport_continent',
            field=models.CharField(default=True, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='airport',
            name='airport_isoCountry',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='airport',
            name='airport_isoRegion',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='airport',
            name='airport_municipality',
            field=models.CharField(default=True, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='airport',
            name='airport_id',
            field=models.CharField(max_length=16, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('flight_id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('flight_departureDate', models.DateField(blank=True, null=True)),
                ('flight_arrivalDate', models.DateField(blank=True, null=True)),
                ('flight_distance', models.IntegerField(default=0)),
                ('flight_aircraft', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.aircraft')),
                ('flight_arrivalAirport', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aa', to='booking.airport')),
                ('flight_departureAirport', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ad', to='booking.airport')),
            ],
        ),
    ]
