# Generated by Django 4.0.4 on 2022-04-28 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_rename_e_class_seats_aircraft_aircraft_eclassseats_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aircraft',
            old_name='aircraft_maintenance',
            new_name='aircraft_maintenanceDate',
        ),
        migrations.RenameField(
            model_name='aircraft',
            old_name='aircraft_maintenance_km',
            new_name='aircraft_maintenanceKm',
        ),
    ]
